version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
         
      - run:
          name: Run Install
          command: |
            . venv/bin/activate
            make install
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make lint
    

workflows:
  sample:
    jobs:
      - build-and-test
